apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mytestapp
  namespace: argocd
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/fangheloiu/Mytestrepo.git
    targetRevision: HEAD
    helm:
      valueFiles: ['values-dev.yaml']
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  
